### ISSUE TITLE
About us -> Inactive about us shows in website 

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/cameo--adminpanel#69]
![image](https://github.com/user-attachments/assets/485d65ea-00dd-4e9d-bbb8-8144960e009e)

![image](https://github.com/user-attachments/assets/5f5e58e7-0c3b-4141-b2a6-12684cb86e5f)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not Fixed

**Comment by Gokilavani-m8** [comment]
Not Fixed

**Comment by Gokilavani-m8** [comment]
Pass
