### ISSUE TITLE
Inactive event category displayed in website

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/cameo--adminpanel#70]
![image](https://github.com/user-attachments/assets/5d568030-9db4-4ac9-8fa9-cc8e5c6f45f6)

![image](https://github.com/user-attachments/assets/917ac8ff-1408-445a-a83b-a8270ba63974)

**Comment by M8Balaji** [comment]
fixed

**Comment by Gokilavani-m8** [comment]
Not Fixed

**Comment by Gokilavani-m8** [comment]
Not Fixed

**Comment by Gokilavani-m8** [comment]
Pass
