### ISSUE TITLE
Inactive blog displayed in website

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/cameo--adminpanel#71]
![image](https://github.com/user-attachments/assets/18b29e6e-960f-44ee-bed9-9f68b4e5604c)

![image](https://github.com/user-attachments/assets/7b2ce9b4-93ab-4246-a46b-3b237a32dca0)

**Comment by M8Balaji** [comment]
Fixed

**Comment by Gokilavani-m8** [comment]
Not fixed

**Comment by Gokilavani-m8** [comment]
Not Fixed

**Comment by Gokilavani-m8** [comment]
Pass
