### ISSUE TITLE
Home Page > Banners List

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/cameo--adminpanel#74]
After clicking on inactive icon for a particular title, in website page the index of page has displayed.

[Recording-20240805_055146.webm](https://github.com/user-attachments/assets/c6b32e31-848b-4c63-b93f-63267d569da3)

**Comment by M8Balaji** [comment]
@Gokilavani-m8

**Comment by Gokilavani-m8** [comment]
Pass
