### ISSUE TITLE
Home Page > We are Cameo, Property, Events, Discounts, Testimonials, Blogs

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/cameo--adminpanel#76]
1. After clicking on inactive status, the index of page has displayed for **We are Cameo, Property, Events, Discounts, Testimonials, Blogs** modules.
2. Events & Testimonials - Loading issue in website page after clicking on inactive status.

**Comment by M8Balaji** [comment]
@Gokilavani-m8 API side issue

**Comment by Gokilavani-m8** [comment]
Pass
