### ISSUE TITLE
Home Page > Discount

### ISSUE THREAD

**Issue by Gokilavani-m8** [Gokilavani-m8/cameo--adminpanel#77]
After adding new discounts and clicking on the save icon, it doesn't reflected on website page.

Website page
![image](https://github.com/user-attachments/assets/2ea1d2c0-db2f-41e2-813f-719b8969332b)

Admin panel page
![image](https://github.com/user-attachments/assets/6f23ba66-e7b2-4ebe-a3e6-ede7ab170149)

**Comment by M8Balaji** [comment]
@Gokilavani-m8  backend issue - https://cameoadmin.m8itsolutions.in/api/home - One data is comming

**Comment by M8Balaji** [comment]
@Gokilavani-m8 Only one discount can be show

**Comment by prabhu** [comment]
Can you stop including me? I am not the person you are looking for

**Comment by M8Balaji** [comment]
> Can you stop including me? I am not the person you are looking for
**Sry for the Inconvience**

**Comment by Gokilavani-m8** [comment]
In Admin Panel, there are 3 discounts are shown. And the 3 discounts are in active status
![Capture5](https://github.com/user-attachments/assets/9c4c8c8f-a17e-4f97-a750-6219f64ef7ff)

But in website, no discount has displayed on the page
![Capture6](https://github.com/user-attachments/assets/f75b9d49-337d-4ef8-8a43-b58e7c055222)

**Comment by Gokilavani-m8** [comment]
Pass
